version: '3.5'

services: 
    apt-builder:
        container_name: apt-builder
        image: openvalverde/ubuntu20.04-deb-images:val-verde-debs-1.0.0
        build: 
            context: ./
            dockerfile: deb.Dockerfile
        environment:
            CLIENT_ID: 8xabfsi4ljd3jstlobi2sfjoj2vtqqjw
            VAL_VERDE_GH_TEAM: val-verde
        privileged: true
