#!/bin/bash

set -e

function get-auth-bearer-info() {
    BEARER_CREDS=$(curl -v --location --request POST 'https://api.box.com/oauth2/token' \
                            --header 'Content-Type: application/x-www-form-urlencoded' \
                            --data-urlencode "client_id=${CLIENT_ID}" \
                            --data-urlencode "client_secret=${CLIENT_SECRET}" \
                            --data-urlencode 'grant_type=client_credentials' \
                            --data-urlencode 'box_subject_type=enterprise' \
                            --data-urlencode "box_subject_id=${ENTERPRISE_ID}")
    ACCESS_TOKEN=$(echo ${BEARER_CREDS} | jq '.access_token')
    EXPIRY_TIME=$(echo ${BEARER_CREDS} | jq '.expires_in')
}

get-auth-bearer-info

function list-folder-contents() {
    BEARER_TOKEN=$(echo ${ACCESS_TOKEN} | tr -d '"')

    curl -v --location --request GET "https://api.box.com/2.0/folders/${FOLDER_ID}" \
           -H 'Content-Type: application/json' \
           -H "Authorization: Bearer ${BEARER_TOKEN}"
}

function get-unsigned-deb-files {
   FOLDER_ID=129384136434 list-folder-contents
}

get-unsigned-deb-files

