#!/bin/bash

set -e

function get-auth-bearer-info() {
    BEARER_CREDS=$(curl -X POST 'https://api.box.com/oauth2/token' \
                            --header 'Content-Type: application/x-www-form-urlencoded' \
                            --data-urlencode "client_id=${CLIENT_ID}" \
                            --data-urlencode "client_secret=${CLIENT_SECRET}" \
                            --data-urlencode 'grant_type=client_credentials' \
                            --data-urlencode 'box_subject_type=enterprise' \
                            --data-urlencode "box_subject_id=${ENTERPRISE_ID}")
    ACCESS_TOKEN=$(echo ${BEARER_CREDS} | jq -r '.access_token')
    EXPIRY_TIME=$(echo ${BEARER_CREDS} | jq -r '.expires_in')
}

get-auth-bearer-info

function list-folder-contents() {
    LIMIT=${LIMIT:-1000}
    OFFSET=${OFFSET:-0}
    FILE_LIST=$(curl -X GET "https://api.box.com/2.0/folders/${FOLDER_ID}/items?limit=${LIMIT}&offset=${OFFSET}" \
                        -H 'Content-Type: application/json' \
                        -H "Authorization: Bearer ${ACCESS_TOKEN}")
    FILE_COUNT=$(echo ${FILE_LIST} | jq length)
    FILE_ENTRIES=$(echo ${FILE_LIST} | jq -r '.entries')
}

function create-folder() {
    curl -i -X POST "https://api.box.com/2.0/folders" \
     -H "Authorization: Bearer ${ACCESS_TOKEN}" \
     -H "Content-Type: application/json" \
     -d '{"name":"'"${NEW_NAME}"'", "parent":{"id":"0"}'
}

function delete-folder() {
    curl -i -X DELETE "https://api.box.com/2.0/folders/${FOLDER_ID}" \
     -H "Authorization: Bearer ${ACCESS_TOKEN}"
}

function get-all-deb-files() {
    FOLDER_ID=129384435209
    list-folder-contents
}

function get-unsigned-deb-files() {
    FOLDER_ID=129384136434
    list-folder-contents

    for i in `seq 0 $(($FILE_COUNT - 1))`; do
        FILE_NAME=$(echo ${FILE_ENTRIES} | jq -r "[.[].name][$i]")
        FILE_ID=$(echo ${FILE_ENTRIES} | jq -r "[.[].id][$i]")
        curl -X GET "https://api.box.com/2.0/files/${FILE_ID}/content" \
                    -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                    -L --output unsigned/${FILE_NAME}
    done
}

function upload-file() {
    curl -i -X OPTIONS "https://api.box.com/2.0/files/content" \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"name":"'"${FILE_NAME}"'", "parent":{"id":"'"${FOLDER_ID}"'"}}'
     curl -i -X POST "https://upload.box.com/api/2.0/files/content" \
             -H "Authorization: Bearer ${ACCESS_TOKEN}" \
             -H "Content-Type: multipart/form-data" \
     -F attributes='{"name":"'"${FILE_NAME}"'", "parent":{"id":"'"${FOLDER_ID}"'"}}' \
     -F filename=@"signed/${FILE_NAME}"
}

function upload-signed-deb-files() {
    FOLDER_ID=129383768201

    for file in signed/*; do
       FILE_NAME=$(echo "$(basename $file)")
       upload-file
    done

}

#upload-signed-deb-files
#get-unsigned-deb-files
